name: CI chain run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:	
  
  
  Docker-build-and-push:
    runs-on: ubuntu-latest
    name: Build and push Docker image to Docker Hub
    #if: github.event_name == 'release'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push the Docker image to Docker hub repository
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ilosim/exercice_devops


