name: CI chain run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:	
  Test:
   runs-on: ubuntu-latest
   name: run app tests
   steps:
    - run: python tests/conftest.py 
    - run: tests/test_articles.py 
    - run: tests/test_authentication.py
    - run: tests/test_config.py
    - run: tests/test_models.py
    - run: tests/test_profile.py
  
  Docker-build-and-push:
    runs-on: ubuntu-latest
    name: Build and push Docker image to Docker Hub
    if: github.event_name == 'release'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push the Docker image to Docker hub repository
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ilosim/exercice_devops


