name: CI chain run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:	
  Test:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - run: tests/conftest.py 
      - run: tests/test_articles.py 
      - run: tests/test_authentication.py
      - run: tests/test_config.py
      - run: tests/test_models.py
      - run: tests/test_profile.py
  
  Docker-build-and-push:
     runs-on: ubuntu-latest
     name: Build and push Docker image to Docker Hub
     if: github.event_name == 'release'
     steps:
      - name: Check out the repo
      - uses: actions/checkout@v2
 
      - name: Login to DockerHub registry
      - uses: actions/checkout@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKERH_USERNAME }} --password-stdin
      
      - name: Build the Docker image 
      - uses: actions/checkout@v1
      - run: docker build . --file Dockerfile --tag flask-app:$(date +%s)

      - name: Push the Docker image to Docker hub repository
      - uses: actions/checkout@v1
      - run: docker push ${{secrets.DOCKER_USERNAME}}/exercice_devops


